(function(){
  const names={
    'TUNEL-AXF':'Tunnel Type Axial Fan','MOB-AXD/ATEX':'Axial Mobile Ex-proof Fan','BOX-AXF':'Axial Cell Type Smoke Extract Fans','ROOF-AXF':'Axial Roof Type Smoke Extract Fans','AXD/ATEX':'Axial Duct Type Ex-proof Fan','AXW/ATEX':'Axial Wall Type Ex-proof Fans','AXR/ATEX':'Axial Roof Type Ex-proof Fan','CRH/ATEX':'Centrifugal Roof Type Ex-proof Fan','CRD/ATEX':'Centrifugal Duct Type Ex-proof Fan','CRS/ATEX':'Centrifugal Single Inlet Ex-proof Fan','AXD/MOB':'Mobile Axial Fan','CRU-EC':'Vertical Outlet Centrifugal Roof Type Fan','CRB-EC':'Centrifugal Rectangular Duct Type Fan','CRC-EC':'Centrifugal Cell Type Fan','CR-EC':'Horizontal Outlet Centrifugal Roof Type Fan','AXF':'Axial Duct Type Smoke Extract Fans','AXJ':'Axial Jet Fan','RXJ':'Radial Jet Fans','AXD':'Axial Duct Type Fan','AXS':'Axial Short Case Fan','AXW':'Axial Wall Type Fan','AXB':'Bifurcated Axial Duct Type Fan','AXH':'Axial Cell Type Fans','AXR':'Horizontal Outlet Axial Roof Type Fan','AXV':'Vertical Outlet Axial Roof Type Fan','CRB':'Centrifugal Rectangular Duct Type Fan','CRD':'Centrifugal Rectangular Duct Type Fan','CRK':'Centrifugal Single Inlet Cell Type Fan','CRC':'Centrifugal Cell Type Fan','CRS':'Centrifugal Single Inlet Fan','CRH':'Horizontal Outlet Centrifugal Roof Type Fan','CRV':'Vertical Outlet Centrifugal Roof Type Fan','CRU':'Vertical Outlet Centrifugal Roof Type Fan','CRR':'Duct Type Shelter Fan','VHR':'Heat Recovery Units','CD':'Centrifugal Duct Type Fan','CR':'Horizontal Outlet Centrifugal Roof Fan'
  };
  const aliases={'MOB-AXD':'AXD/MOB','AXD-MOB':'AXD/MOB','AXD/MOB':'AXD/MOB'};
  const files={};Object.keys(names).forEach(code=>files[code]=code.replaceAll('/','-')+'.webp');
  Object.assign(files,{'TUNEL-AXF':'TUNEL-AXF.webp','MOB-AXD/ATEX':'MOB-AXD-ATEX.webp','BOX-AXF':'BOX-AXF.webp','ROOF-AXF':'ROOF-AXF.webp','AXD/MOB':'MOB-AXD.webp'});
  const keys=[...new Set([...Object.keys(names),...Object.keys(aliases)])].sort((a,b)=>b.length-a.length);
  function normalize(value){return String(value||'').toUpperCase().replace(/\\/g,'/').replace(/\s+/g,' ').trim()}
  function seriesCode(value){const text=normalize(value);const found=keys.find(k=>text===k||text.startsWith(k+' ')||text.startsWith(k+'-')||text.includes(' '+k+' '));return aliases[found]||found||''}
  function normalizeModel(value,code){let model=String(value||'').trim();if(code==='AXD/MOB')model=model.replace(/^MOB-AXD(?=\s|-)/i,'AXD/MOB').replace(/^AXD-MOB(?=\s|-)/i,'AXD/MOB');return model}
  function imageFor(code){return code&&files[code]?'assets/products/'+files[code]:''}
  function fromModel(row){
    const code=seriesCode(row?.series||row?.model),info=row?.catalogueInfo||{},model=normalizeModel(row?.model||row?.display||'',code);
    return {id:String(row?.key||model),model,series:{code,title:names[code]||row?.catalogNameEn||row?.series||''},media:{image:imageFor(code)},description:{general:info.general||[],motor:info.motor||[],applications:info.applications||[]},pricing:{listPrice:Number.isFinite(Number(row?.price))?Number(row.price):null,currency:'EUR'},technical:{motorPower:Number(row?.kw)||0,speed:Number(row?.rpm)||0,current:Number(row?.amps)||0,sound:Number(row?.spl)||0,voltage:row?.voltage||'',atex:Boolean(row?.atex),fireClass:row?.fire||'',sourcePage:row?.sourcePage||'',tags:row?.tagsEn||row?.tags||[]},performance:{nominalAirflow:Number(row?.nominal)||0,points:row?.points||[]}};
  }
  const records=new Map();(window.models||[]).forEach(m=>records.set(String(m.key),fromModel(m)));
  window.VensisProducts={get:key=>records.get(String(key||''))||null,fromResult:r=>records.get(String(r?.key||''))||fromModel(r||{}),seriesCode,seriesName:value=>names[seriesCode(value)]||'',image:value=>imageFor(seriesCode(value)),count:()=>records.size};
})();